#!/bin/bash
# copy this file to virtualenv bin at bin/gunicorn_start
# set executable bit with: $ sudo chmod u+x bin/gunicorn_start

NAME="thor_app"                                  # Name of the application
DJANGODIR=/webapps/thor/thor_app             # Django project directory
SOCKFILE=/webapps/thor/run/gunicorn.sock  # we will communicte using this unix socket
USER=thor                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=thor_app.settings.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=thor_app.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
