"""
Django settings for thor_app project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import private

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = private.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = private.DEBUG

ALLOWED_HOSTS = private.ALLOWED_HOSTS


LOGIN_URL = '/admin/login/'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'life_log',
    'django_extensions',
    'storages',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'thor_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/ubuntu/webapps/thor/thor_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/home/ubuntu/webapps/thor/thor_app/log/thor_app.log',
            'formatter': 'verbose',
            'maxBytes': 1024 * 1024 * 10, # 10 MB
            'backupCount': 10,
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'thor_app': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'life_log': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}



WSGI_APPLICATION = 'thor_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = private.DATABASES


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = '/assets/'
MEDIA_ROOT = '/media/'
AWS_STORAGE_BUCKET_NAME = 'webapp-assets'
S3_URL = 'http://s3.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME
STATIC_URL = S3_URL + STATIC_ROOT
STATICFILES_STORAGE = 'main.s3utils.StaticS3BotoStorage'
DEFAULT_FILE_STORAGE = 'main.s3utils.StaticS3BotoStorage'

MEDIA_URL = S3_URL + MEDIA_ROOT

#    STATICFILES_DIRS = ('/webapps/thor/thor_app/assets/',)
#STATIC_ROOT = '/home/ubuntu/webapps/thor/thor_app/assets/'
STATIC_ROOT = 'http://s3.amazonaws.com/%s/assets/' % AWS_STORAGE_BUCKET_NAME

# Sessions
SESSION_COOKIE_AGE = 60 * 60 * 2 # 2 hours
